name = "landing_page"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
sketch = {path = "../sketch"}
sketch_redraw = {path = "../sketch_redraw"}
redraw = ">= 19.0.6 and < 20.0.0"
redraw_dom = ">= 19.0.6 and < 20.0.0"

[dev-dependencies]
gleeunit = ">= 1.5.0 and < 2.0.0"
