name = "shared_view"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
sketch = { path = "../../sketch" }
sketch_lustre = { path = "../../sketch_lustre" }
lustre = ">= 4.3.1 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
